#undef _RANK_LABEL2
#define _RANK2 0
#define _RANK_LABEL2
#include "../inc/type1.inc"
#undef _RANK2
#undef _RANK_LABEL2
#define _RANK_LABEL2 _RANK2
#if _MAX_RANK >= 1
#  define _RANK2 1
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 2
#  define _RANK2 2
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 3
#  define _RANK2 3
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 4
#  define _RANK2 4
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 5
#  define _RANK2 5
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 6
#  define _RANK2 6
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 7
#  define _RANK2 7
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 8
#  define _RANK2 8
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 9
#  define _RANK2 9
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 10
#  define _RANK2 10
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 11
#  define _RANK2 11
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 12
#  define _RANK2 12
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 13
#  define _RANK2 13
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 14
#  define _RANK2 14
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#if _MAX_RANK >= 15
#  define _RANK2 15
#  include "../inc/type1.inc"
#  undef _RANK2
#endif
#undef _RANK_LABEL2
